version: '3.1'
services:
  nginx:
    image: nginx:1.17.6
    ports:
      - 80:80
    networks:
      movie-network:
        aliases:
          - movie-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chris:movie
    container_name: app-movie-1
    networks:
      movie-network:
        aliases:
          - movie-app
    volumes:
      - ./db:/app/db
networks:
  movie-network:
